from os.path import join,expanduser
import os

tooldir = '../waftool'

def options(opt):
    opt.load('compiler_cxx')
    opt.load('conda', tooldir=tooldir)
    opt.load('cflags', tooldir=tooldir)
    opt.load('yaml-cpp', tooldir=tooldir)

def configure(conf):
    conf.load('compiler_cxx')
    conf.load('conda', tooldir=tooldir)
    conf.conda_boost()
    conf.load('cflags', tooldir=tooldir)
    conf.load('yaml-cpp', tooldir=tooldir)
    conf.check_yaml_cpp()

def build(bld):
    bld.shlib(
        source = ['reader.cxx', 'error.cxx', 'node.cxx'],
        target = 'numini', 
        includes = '.',
        use = 'YAML-CPP BOOST'
    )

    bld.install_files(
        '${PREFIX}/include/numini',
        ['reader.hxx', 'reader.txx', 'error.hxx', 'node.hxx'],
    )
