from os.path import expanduser
import os

tooldir = '../waftool'
os.environ['WAF_TOOLDIR'] = tooldir

def options(opt):
    opt.load('use_config')
    opt.load('compiler_cxx')
    opt.load('conda', tooldir=tooldir)
    opt.load('numini', tooldir=tooldir)

def configure(conf):
    from waflib.extras import use_config
    use_config.DEFAULT_DIR = 'config'
    conf.load('use_config')

    conf.load('compiler_cxx')
    conf.load('conda', tooldir=tooldir)
    conf.conda_boost()
    conf.load('numini', tooldir=tooldir)
    conf.check_numini()

def build(bld):
    bld.program(
        source = 'main.cxx',
        target = 'main',
        use = 'NUMINI YAML-CPP',
    )
