def options(opt):
        opt.load('compiler_cxx')

def configure(conf):
        conf.load('compiler_cxx')

def build(bld):
        bld.program(source='main.cxx', target='main', lib='numini yaml-cpp')

