package:
  name: numini
  version: 0.0.0

source:
  git_url: https://github.com/dfroger/numini

build:
  number: 2
  binary_relocation: false

requirements:
  build:
    - boost
    - yaml-cpp
  run:
    - boost
    - yaml-cpp

about:
  home: https://github.com/dfroger/numini
  license: GPL
