package:
  name: numini
  version: 0.2.0

source:
  path: ..
  # fn: numini-0.2.0.tar.gz
  # url: https://github.com/dfroger/numini/archive/0.2.0.tar.gz

build:
  number: 0 # [osx]
  number: 0 # [linux]
  binary_relocation: true

requirements:
  build:
    - boost
    - yaml-cpp
    - waf
    - pkg-config # [osx]
  run:
    - boost
    - yaml-cpp
    - waf

about:
  home: https://github.com/dfroger/numini
  license: GPL
  summary:  Configuration file for numerical simulation code

