package:
  name: numini
  version: 0.1.0

source:
  fn: numini-0.1.0.tar.gz
  url: https://github.com/dfroger/numini/archive/0.1.0.tar.gz

build:
  number: 0
  binary_relocation: true

requirements:
  build:
    - boost
    - yaml-cpp
    - waf
  run:
    - boost
    - yaml-cpp
    - waf

about:
  home: https://github.com/dfroger/numini
  license: GPL
  summary:  Configuration file for numerical simulation code

